version: '3.5'

services:
  vmq-redis-backup:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/mqtt/vmq-redis-backup}:${IMAGE_TAG:-latest}
    environment:
      REDIS_HOST:
      REDIS_PORT:
      BACKUP_PATH:
      AWS_BUCKET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      PUSHGATEWAY_HOST:
      PUSHGATEWAY_JOB:
    networks:
      - vernemq-net
      - metric-net
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: ${RESTART_DELAY:-10s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  vernemq-net:
    name: ${VERNEMQ_NET_NAME:-vernemq-net}
    driver: ${VERNEMQ_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
